NumPy (Numerical Python) is a core library in Python for numerical computations. It provides support for arrays, matrices, and high-level mathematical functions to operate on these structures efficiently.


NumPy

Purpose: Numerical computations and array operations.

Why Use It?

Python’s built-in lists are versatile but slow for mathematical operations. NumPy provides multi-dimensional arrays (like matrices) that are highly efficient for computation.
It includes functions for mathematical operations, linear algebra, random number generation, and more.

Key Features:

Arrays: A replacement for Python lists, with better performance.
Mathematical operations: Perform element-wise operations, matrix multiplication, etc.
Built-in functions: For mathematical, statistical, and logical operations.

In [ ]:
#pip install numpy

import numpy as np
#Create an array
arr = np.array([1,2,32,4,5,6,7])
#Perform Operations
print(arr+10)
print(arr-1)
print(arr*2)
print(arr/2)
print(arr)
print(arr.mean())

[11 12 42 14 15 16 17]
[ 0  1 31  3  4  5  6]
[ 2  4 64  8 10 12 14]
[ 0.5  1.  16.   2.   2.5  3.   3.5]
[ 1  2 32  4  5  6  7]
8.142857142857142


In [7]:
#Create a 2D Array
matrix=np.array([[1,2],[3,4]])
print(matrix * 2) #Element wise Multiplication

[[2 4]
 [6 8]]


In [10]:
#Zeros, Ones and Empty Arrays
zeros = np.zeros((2,3))
ones=np.ones((3,3))
empty=np.empty((2,2))
print(zeros)
print(ones)
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1.e-323 2.e-323]
 [3.e-323 4.e-323]]


In [19]:
#Arrange and Linespace
arange = np.arange(0,10,2)
print(arange)
linspace = np.linspace(0,1,5)
print(linspace)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [22]:
#Array Attributes and Operations
#Attributes
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [24]:
#Array Operations
#Arithmetic Operation
arr1=np.array([2,3,5])
arr2=np.array([8,9,4])
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)

[10 12  9]
[16 27 20]
[-6 -6  1]
[0.25       0.33333333 1.25      ]


In [26]:
#Statistical Operations
arr = np.array([[1,2],[4,5]])
print(arr.sum())
print(arr.mean())
print(arr.std())


12
3.0
1.5811388300841898


In [28]:
#Indexing and Slicing
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:4])

[2 3 4]


In [30]:
#Advanced Concepts
#Broadcasting : Allows arithmetic operations on arrays of different shapes.

a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [33]:
#Reshaping
arr = np.arange(8)
reshaped=arr.reshape(2,4)
print(reshaped)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


In [36]:
#Transpose
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [48]:
#Random Number Generation
rand = np.random.rand(3,2)
print(rand)
randn=np.random.randn(3,2)
print(randn)
integers = np.random.randint(1,10,(2,2))
print(integers)

[[0.91051546 0.48632063]
 [0.28805809 0.99715327]
 [0.88690737 0.87967904]]
[[ 2.00001204  0.26112615]
 [ 0.56823792  1.19887098]
 [ 0.99866594 -0.92920103]]
[[5 4]
 [2 2]]
